name: Quizz Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into Server & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export DOPPLER_TOKEN=${{ secrets.DOPPLER_ACCESS_KEY }}
            cd ~/quizz
            git pull
            git reset --hard origin/main
            doppler secrets download --no-file --format env > internal/config/.env 
            docker-compose up -d --build
